---
# tasks file for ansible-keepalived
## INSTALLATION ##
- include: keepalived_install.yml
  when:
    ansible_distribution == 'Ubuntu'
    and ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial'
  tags: [installation]

## ROLLBACK ##
- include: keepalived_rollback.yml
  when:
    ansible_distribution == 'Ubuntu'
    and ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial'
  tags: [rollback]

## TESTING ##
- include: keepalived_testing.yml
  when:
    ansible_distribution == 'Ubuntu'
    and ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial'
  tags: [testing]
